---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-test-deployment # <-- Must match rollout status command
  labels:
    app: kind-ci-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kind-ci-test
  template:
    metadata:
      labels:
        app: kind-ci-test
    spec:
      containers:
      - name: nginx
        image: nginx:latest 
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ci-test-service # <-- Must match kubectl get svc command
spec:
  selector:
    app: kind-ci-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
