Run kubectl apply -f deployment.yaml
  kubectl apply -f deployment.yaml
  shell: /usr/bin/bash -e {0}
error: error validating "deployment.yaml": error validating data: apiVersion not set; if you choose to ignore these errors, turn validation off with --validate=false
Error: Process completed with exit code 1.
